Reverting BC update - causes exception
Exception java.lang.NoSuchMethodError: org.bouncycastle.asn1.x509.SubjectPublicKeyInfo.getPublicKeyData()Lorg/bouncycastle/asn1/DERBitString